temperature: 1
temperature_scheduler: null
hard_label_weight: 0.0
hard_loss_type: ce
hard_label_weight_scheduler: null
kd_loss_weight: 1.0
kd_loss_type: ce
kd_loss_scheduler: null
probability_shift: False
intermediate_matches:
  - null
